### PR TITLE
implemented (naive) buffer rotation

### PR DESCRIPTION
**Pull request by christophevg**
Added rotation to buffer, using newly introduced unit2led(x,y) conversion. The latter might benefit from a decent algorithm, now it takes a constant HEXAGON_LED_COUNT sqrts :-(

### CODE REVIEW

**Comment by aliekens** [comment]
Would love to see a sample app that demonstrates its use. Hard to accept without some sort of testing, even if it is seeing a nice new demo app ;) (I know this is part of something bigger)

As it stands, rotating a buffer requires the user to create a new one. If users rotate like crazy, they are likely to cause mayhem and generate memory leaks. If `Buffer::rotate()` is implemented as a mutating instead of non-mutating method, we can isolate memory handling for a temporary buffer. 

Also, there will certainly be use cases for a non-mutating version (they could be used complementary), too, but I would write it as `Buffer* Buffer::rotate( double angle )` and have the rotated buffer returned, instead of the proposed approach that reminds me of C.

I do like the `unit2led()` plan. I'm pondering optimizations, now, too (is there something like a hexagonal version of binary search???) but would love to merge that as is.

**Comment by aliekens** [comment]
BTW no need to compute the `sqrt`s because you can also look for the smallest distance squared.

**Comment by christophevg** [comment]
See my current HeXXXagon experiment in the hexxxagon branch in https://github.com/christophevg/hexxx/tree/hexxxagon

minimal survival commands:
```bash
$ cd /tmp
$ git clone https://github.com/christophevg/hexxx
...
$ cd hexxx
$ git checkout hexagon
...
$ make run-hexxxagon_simulator
...
```

**Comment by christophevg** [comment]
BTW there is a good reason why I didn't implement it mutating ... see example for a typical use case.

**Comment by christophevg** [comment]
I've added a mutating version, which doesn't use heap memory. I don't think that only this version is good enough. The non-mutating version is also important (e.g. when we add + operator on buffer). Also, returning Buffer\* is also bad, because this means you're creating a `new` object in that method, but don't control the `free`ing afterwards, which _will_ lead to memory leaks. (The only reason to `return this` might be to allow for method chaining.)

I've removed the `sqrt` call.

And I've added an example, in an examples/ folder, to start cleaning up the directory structure a bit. The `Makefile` has support for this also:

``` bash
$ make examples/rotating_buffer_simulator
...
$ make run-example-rotating_buffer_simulator
...
```

**Pull request merged**
