### PR TITLE
X ycordinates

### PR DESCRIPTION
**Pull request by borissmidt**
I already created the slanted cordinate system if you want it. 
And an API for that. plus a drawing of a beer glas.

### CODE REVIEW

**Comment by aliekens** [comment]
Uargh, ik heb net conflicting commits gedaan met mijn coordinate overhaul ...

**Comment by borissmidt** [comment]
how come?

**Comment by aliekens** [comment]
I just moved all of the coordinate stuff to arrays+functions, so it's changed all over the place.

**Comment by borissmidt** [comment]
Its sad that you are now unable to test the drawing API :(

**Comment by aliekens** [comment]
I tried compiling it, but there's a few problems.

The Makefile needs tabs instead of spaces. Also, I'm getting an error here:

```
g++  -std=c++0x -O2  -c -o coordinates.o coordinates.cpp
coordinates.cpp:56:1: error: too many initializers for ‘int [397][2]’
```

**Comment by borissmidt** [comment]
make it 400 and it might work.  i havn't been able to test the code because i do not have a hex. nor can i find my RPI

**Comment by aliekens** [comment]
Maybe it's better to hold off pull requests until proven to work on the HEXXX itself ... unless we get a good emulator running. Too bad Open Garage has a week of no Open Garage ...

I have a whole bunch of TODOs on the HEXX that I want to go through in the next few days which will very likely break any pull requests coming in now ... I will definitely be taking parts of your pull request but it'll be easier to copy code rather than merge atm.

**Comment by aliekens** [comment]
Of course, I'll drop in credits where due.

**Comment by borissmidt** [comment]
thats good can you atleast try to get a somewhat equal API? and the beer code becasue i really wonder if it worked or not.

**Comment by aliekens** [comment]
It's really hard to work with commits that don't compile while I have 300 things on my mind.

I'm definitely not pulling if it doesn't compile, but here's a heads up on why the beer will not be for immediately ...

```
g++  -std=c++0x -O2  -c -o coordinates.o coordinates.cpp
g++  -std=c++0x -O2  -c -o draw.o draw.cpp
In file included from ws2811/ws2811.h:35:0,
                 from draw.h:3,
                 from draw.cpp:1:
ws2811/pwm.h:58:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:74:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:88:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:92:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:93:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:94:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:95:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:96:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:97:5: error: ‘uint32_t’ does not name a type
ws2811/pwm.h:98:5: error: ‘uint32_t’ does not name a type
In file included from draw.h:3:0,
                 from draw.cpp:1:
ws2811/ws2811.h:42:9: error: ‘uint32_t’ does not name a type
ws2811/ws2811.h:49:5: error: ‘ws2811_led_t’ does not name a type
ws2811/ws2811.h:55:5: error: ‘uint32_t’ does not name a type
In file included from draw.cpp:1:0:
draw.h:10:71: error: ‘ws2811_led_t’ has not been declared
draw.h:12:58: error: ‘ws2811_led_t’ has not been declared
draw.h:15:48: error: ‘ws2811_led_t’ has not been declared
In file included from hexxx.h:28:0,
                 from draw.cpp:3:
color.h:7:1: error: ‘ws2811_led_t’ does not name a type
color.h:8:23: error: ‘ws2811_led_t’ does not name a type
color.h:8:36: error: ISO C++ forbids declaration of ‘color’ with no type [-fpermissive]
color.h:9:25: error: ‘ws2811_led_t’ does not name a type
color.h:9:38: error: ISO C++ forbids declaration of ‘color’ with no type [-fpermissive]
color.h:10:24: error: ‘ws2811_led_t’ does not name a type
color.h:10:37: error: ISO C++ forbids declaration of ‘color’ with no type [-fpermissive]
color.h:17:1: error: ‘ws2811_led_t’ does not name a type
color.h:18:1: error: ‘ws2811_led_t’ does not name a type
color.h:20:1: error: ‘ws2811_led_t’ does not name a type
color.h:21:1: error: ‘ws2811_led_t’ does not name a type
In file included from draw.cpp:3:0:
hexxx.h:43:30: error: ‘ws2811_led_t’ has not been declared
hexxx.h:44:1: error: ‘ws2811_led_t’ does not name a type
hexxx.h:46:12: error: variable or field ‘fill’ declared void
hexxx.h:46:12: error: ‘ws2811_led_t’ was not declared in this scope
hexxx.h:47:19: error: variable or field ‘fillhexagon’ declared void
hexxx.h:47:19: error: ‘ws2811_led_t’ was not declared in this scope
hexxx.h:48:18: error: variable or field ‘fillborder’ declared void
hexxx.h:48:18: error: ‘ws2811_led_t’ was not declared in this scope
draw.cpp:7:71: error: ‘ws2811_led_t’ has not been declared
draw.cpp:44:60: error: ‘ws2811_led_t’ has not been declared
draw.cpp:97:48: error: ‘ws2811_led_t’ has not been declared
<builtin>: recipe for target 'draw.o' failed
make: *** [draw.o] Error 1
```

**Comment by aliekens** [comment]
API is still changing a lot. Everything will be overhauled to C++ classes at one point, so nothing is certain. Hard to guarantee anything at this moment.

**Comment by borissmidt** [comment]
i wonder why you would use an draw class , maybe a hexagon class but then you have to create a class for every shape, while a function for each shape defined by its points would seem enough.

and the errors seem to be in your project code not mine. maybe my makefile define isn't correct and the includes don't get used.

**Comment by aliekens** [comment]
It will evolve into a LEDString class with methods, instead of class-less functions. Now it's C-like code in a C++ environment, I need to seriously improve on that.

**Comment by borissmidt** [comment]
That might be handly so you can set draw color seperatly and keep on drawing in the same color. 

if you need any help you can always ask.

**Comment by aliekens** [comment]
For example, yes. But that means the API is very much undefined until I can refactor the whole shebang. Now, I need my time to hack the planet before CCC so it's all a little dirty ;)

**Comment by borissmidt** [comment]
yea thats why i wanted to create this simple API and emulator to just draw lines and see the output on a virtual board. So people could develop shopes without the HEXX board and thus you can show of more stuff on the board made by different people.

**Comment by aliekens** [comment]
There is now a skewed axis coordinate system, my origin is different from yours. I have now also included my generator code (in Ruby).

I have also uploaded the lasercuttable designs as their Inkscape source SVG files. 

Extra stuff, like generators and SVGs are to be found in `/util`

**Comment by borissmidt** [comment]
if you need any help in developing somekind of API then let me know. 
Also the draw API functions are still compatible with the new coordinate system, But the beer.cpp will not work because my coordinate system was not centered in the middle.

**Pull request closed without merging**
